server:
  port: 5010

spring:
  application:
    name: Food-Order
  cloud:
    discovery:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/item
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
